// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  featured_products: dynamic(() => import("./FeaturedProducts")),
  header: dynamic(() => import("./Header")),
  image_with_text: dynamic(() => import("./ImageWithText")),
  news_letter: dynamic(() => import("./NewsLetter")),
  slider: dynamic(() => import("./Slider")),
};
